remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Maryam Masood"
description: "CS Student Flutter Developer & passionate  about building user-friendly mobile applications and smart solutions"
